baseURL = "http://amoshyc.github.io/blog"
languageCode = "en-us"
title = "Yu-Cheng Huang"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "↩"
uglyurls = true
preserveTaxonomyNames = true
googleAnalytics = "UA-96104654-1"

[params]
    avatar = "abouts/me.jpg"
    anchor = true