baseURL = "http://amoshyc.github.io/blog"
languageCode = "en-us"
title = "Yu-Cheng Huang"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "↩"
uglyurls = true
preserveTaxonomyNames = true
googleAnalytics = "UA-96104654-1"
disqusShortName = "amoshyc-blog"

[blackfriday]
    fractions = false
    extensions = ["hardLineBreak"]

[params]
    avatar = "abouts/me.jpg"
    anchor = true
    author = "amoshyc"
